# Site wide configuration

title: "VEIDA Lab"
description: "VEIDA Lab - York University."
logo: veida-logo-on-depth-120x120.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - html-proofer
  - jekyll-seo-tag

# Site owner
owner:
  name: Brad Stimpson
  email: brad@cse.yorku.ca
  twitter: bstimpson
  google:
    ad-client:
    ad-slot:
  bio: 
  avatar: https://raw.githubusercontent.com/bradstimpson/bradstimpson.github.io/master/assets/images/profile.png # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
